server:
  port: 8000

spring:
  application:
    name: report-service

  datasource:
    url: jdbc:mysql://localhost:3306/trcv_sat
    username: root
    password: trcvbr18
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  swagger-ui:
    path: /report-service/swagger-ui.html

app:
  token:
    secret-key: ${JWT_SECRET_KEY:dHJhY2V2aWEtcmVwb3J0LXNlcnZpY2UtdG9rZW4xOTAw}



